spring:
  datasource:
    url: jdbc:mysql://localhost:3307/product_db?useSSL=false&serverTimezone=UTC
    username: product_user
    password: product_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Let Liquibase manage the schema
    show-sql: true