server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/product_db?useSSL=false&serverTimezone=UTC
    username: product_user
    password: product_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false

logging:
  level:
    liquibase: DEBUG
